version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a Reversi.zip %APPVEYOR_BUILD_FOLDER%\Reversi\bin\Release\*.*
artifacts:
- path: Reversi.zip
  name: Reversi.zip
test:
  assemblies: '**\*.Tests.dll'
